# Generated by Django 3.2.11 on 2022-03-04 11:49

import api.photo_model
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='指导员姓名')),
                ('army', models.CharField(max_length=50, verbose_name='指导员所在部队')),
                ('telephone', models.CharField(max_length=20, verbose_name='指导员联系方式')),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='战士姓名', max_length=50, verbose_name='战士姓名')),
                ('army', models.CharField(max_length=50, verbose_name='战士所在部队')),
                ('telephone', models.CharField(max_length=20, verbose_name='战士联系方式')),
            ],
            options={
                'db_table': 'soldier',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='靶位名称')),
            ],
            options={
                'db_table': 'target',
            },
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='用户姓名')),
                ('army', models.CharField(default='', max_length=255, verbose_name='用户所在部队')),
                ('telephone', models.CharField(default='', max_length=255, verbose_name='用户联系方式')),
                ('target', models.CharField(default='', help_text='仅战士用户填写', max_length=255, verbose_name='用户所选靶位')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.userbase')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.userbase',),
        ),
        migrations.CreateModel(
            name='Goshooting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_dtime', models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 49, 33, 217953, tzinfo=utc), default='', verbose_name='打靶结束时间')),
                ('start_dtime', models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 49, 33, 217953, tzinfo=utc), default='', verbose_name='打靶开始时间')),
                ('shooting_data', models.DateField(default='', verbose_name='打靶日期')),
                ('gtarget', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gtarget', to='api.target')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'go_shooting',
            },
        ),
        migrations.CreateModel(
            name='SelectTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_dtime', models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 49, 33, 219952, tzinfo=utc), default='', verbose_name='打靶结束时间')),
                ('start_dtime', models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 49, 33, 219952, tzinfo=utc), default='', verbose_name='打靶开始时间')),
                ('creat_dtime', models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 49, 33, 219952, tzinfo=utc), default='', verbose_name='成绩生成时间')),
                ('shooting_data', models.DateField(default='', verbose_name='打靶日期')),
                ('simage', models.ImageField(null=True, upload_to='spic/', verbose_name='真实靶图')),
                ('vimage', models.ImageField(null=True, upload_to='vpic/', verbose_name='虚拟靶图')),
                ('score', models.CharField(default='', max_length=10, verbose_name='打靶成绩')),
                ('direction', models.CharField(default='', max_length=50, verbose_name='打靶方位')),
                ('solider', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soldier', to='api.soldier')),
                ('target', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='api.target')),
            ],
            options={
                'db_table': 'select_target',
                'unique_together': {('solider', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(null=True, upload_to=api.photo_model.photo_image_file_path)),
                ('score', models.CharField(default='', max_length=10)),
                ('direction', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_dtime', models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 49, 33, 217953, tzinfo=utc), default='', verbose_name='成绩生成时间')),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=10, max_length=4, verbose_name='打靶环值')),
                ('direction', models.CharField(default='', max_length=50, verbose_name='打靶方位')),
                ('simage', models.ImageField(null=True, upload_to='spic/', verbose_name='真实靶图')),
                ('vimage', models.ImageField(null=True, upload_to='vpic/', verbose_name='虚拟靶图')),
                ('atarget', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atarget', to='api.target')),
                ('goshooting', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goshooting', to='api.goshooting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
    ]
