# Generated by Django 3.2.11 on 2022-03-04 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='type',
            field=models.IntegerField(choices=[(0, '普通指导员'), (1, '超级指导员')], default=0, verbose_name='指导员等级'),
        ),
        migrations.AddField(
            model_name='target',
            name='type',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '使用中')], default=0, verbose_name='靶位使用状态'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='creat_dtime',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 59, 39, 39671, tzinfo=utc), default='', verbose_name='成绩生成时间'),
        ),
        migrations.AlterField(
            model_name='goshooting',
            name='end_dtime',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 59, 39, 39671, tzinfo=utc), default='', verbose_name='打靶结束时间'),
        ),
        migrations.AlterField(
            model_name='goshooting',
            name='start_dtime',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 59, 39, 39671, tzinfo=utc), default='', verbose_name='打靶开始时间'),
        ),
        migrations.AlterField(
            model_name='selecttarget',
            name='creat_dtime',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 59, 39, 41693, tzinfo=utc), default='', verbose_name='成绩生成时间'),
        ),
        migrations.AlterField(
            model_name='selecttarget',
            name='end_dtime',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 59, 39, 41693, tzinfo=utc), default='', verbose_name='打靶结束时间'),
        ),
        migrations.AlterField(
            model_name='selecttarget',
            name='start_dtime',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 3, 4, 11, 59, 39, 41693, tzinfo=utc), default='', verbose_name='打靶开始时间'),
        ),
    ]
